### ISSUE TITLE
juuni 2024 lisatahvlid

### ISSUE THREAD

**Issue by UlleKr** [memoriaal/repis2web#6]
Lõplikud nimekirjad siin:

- [L25](https://docs.google.com/spreadsheets/d/1Gp9DsXN8oOS1uFeq2wKA0Zo7R0wkYZgySalqeWdXMyM/edit#gid=1058235603)
- [L26](https://docs.google.com/spreadsheets/d/1Gp9DsXN8oOS1uFeq2wKA0Zo7R0wkYZgySalqeWdXMyM/edit#gid=1077998696)

**Comment by mitselek** [comment]
praegu on 102 nime?

**Comment by UlleKr** [comment]
??


Kontakt Mihkel Putrinš ***@***.***>) kirjutas kuupäeval E,
8. aprill 2024 kell 15:52:

**Comment by GeorgAndreller** [comment]
Proov

**Comment by mitselek** [comment]
ühendus

mihkel
5656 0978

**Comment by mitselek** [comment]
Lõplikud nimekirjad siin:

- [L25](https://docs.google.com/spreadsheets/d/1Gp9DsXN8oOS1uFeq2wKA0Zo7R0wkYZgySalqeWdXMyM/edit#gid=1058235603)
- [L26](https://docs.google.com/spreadsheets/d/1Gp9DsXN8oOS1uFeq2wKA0Zo7R0wkYZgySalqeWdXMyM/edit#gid=1077998696)
